### PR TITLE
feat: add Stale Bot support

### LINKED ISSUE #13: Create Bot for closing old/stale issues
I'm assuming this is something that can be done with github action or similar
this is to declutter the noise and help focus on addressing actual issues

### PR DESCRIPTION
**Pull request by DrFaust92**
## Description

Add Stale Bot Configuration

## Motivation and Context

Allow for automatically marking stale issues and closing them.
I've set this only for tagging issues after 60 days at the moment, we can add closure and PRs later
Closes #13 

## Breaking Changes

No

## How Has This Been Tested?

No

### CODE REVIEW

**Comment by DrFaust92** [comment]
@antonbabenko, any repo we would like to test this with? i can configure the bot for it.

**Comment by antonbabenko** [comment]
Please send such PR directly to notify-slack repo, where we can merge it and test it before rolling on all repos here.

Also, if your config is different from the one from the EKS module, let's try to make it the same. Or is it the same?

**Comment by DrFaust92** [comment]
i see that its different, ill change it up and open PR for slack module

**Comment by DrFaust92** [comment]
Done terraform-aws-modules/terraform-aws-notify-slack#77

**Comment by DrFaust92** [comment]
Small mistake, moved the file to .github folder: terraform-aws-modules/terraform-aws-notify-slack#78

**Comment by DrFaust92** [comment]
seems to be working nicely for the slack module, albeit you have to configure color of the label manually. we should change to yellow/red.

**Comment by antonbabenko** [comment]
Yes, it works.

What do you think if we configure the stale bot to not touch PRs and only process issues? The reason for this is that there are some PRs which are pretty good and it is better to spend some efforts to finish them and merge (or close).

I have processed some PRs in several modules today but I don't have time to go through all of them (including yours) so do not hesitate to jump in and review/suggest/finish them.

**Comment by DrFaust92** [comment]
That was the initial config but I changed it to align with EKS module, I
agree regarding PRs I'll remove the PR stale section.

**Comment by DrFaust92** [comment]
added filter for issues only.

**Pull request merged**
